# Generated by Django 2.2.1 on 2019-05-15 11:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('id_prerequisite', models.IntegerField(default=0, verbose_name='ID prerequisite')),
                ('background_color', models.CharField(max_length=10, verbose_name='Background color')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Company')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('user_points', models.IntegerField(verbose_name=0)),
                ('avatar', models.CharField(max_length=255)),
                ('id_offers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Offers')),
            ],
        ),
        migrations.CreateModel(
            name='Qa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512, verbose_name='Question')),
                ('answer_1', models.CharField(max_length=40, verbose_name='Answer 1')),
                ('answer_2', models.CharField(max_length=40, verbose_name='Answer 2')),
                ('answer_3', models.CharField(max_length=40, verbose_name='Answer 3')),
                ('answer_4', models.CharField(max_length=40, verbose_name='Answer 4')),
                ('answer_right', models.IntegerField(verbose_name='Right answer')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
        ),
        migrations.CreateModel(
            name='OffersPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promocode', models.CharField(max_length=100, null=True, verbose_name='Promocode')),
                ('purchase_day', models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 15, 11, 26, 19, 919724), verbose_name='Purchase day')),
                ('id_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Offers')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupsPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Points')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
