# Generated by Django 2.2.1 on 2019-05-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('image_name', models.CharField(default='', max_length=60, verbose_name='Image name')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
    ]
