# Generated by Django 2.2.1 on 2019-05-13 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerspurchases',
            name='promocode',
            field=models.CharField(max_length=100, null=True, verbose_name='Promocode'),
        ),
        migrations.AlterField(
            model_name='offerspurchases',
            name='purchase_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 13, 14, 32, 40, 6111), verbose_name='Purchase day'),
        ),
    ]
