# Generated by Django 2.2.1 on 2019-05-13 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190513_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerspurchases',
            name='purchase_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 13, 14, 55, 38, 175822), verbose_name='Purchase day'),
        ),
    ]
