# Generated by Django 2.2.1 on 2019-05-13 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190513_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerspurchases',
            name='purchase_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 13, 14, 58, 29, 916104), verbose_name='Purchase day'),
        ),
    ]
