# Generated by Django 2.2.1 on 2019-05-13 15:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20190513_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerspurchases',
            name='id_user',
        ),
        migrations.AddField(
            model_name='offerspurchases',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerspurchases',
            name='purchase_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 13, 15, 12, 43, 765872), verbose_name='Purchase day'),
        ),
    ]
