# Generated by Django 2.2.1 on 2019-05-13 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190513_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerspurchases',
            name='purchase_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 0, 0, 32, 211864), verbose_name='Purchase day'),
        ),
    ]
