# Generated by Django 2.2.1 on 2019-05-14 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190514_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerspurchases',
            name='purchase_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 20, 2, 55, 436390), verbose_name='Purchase day'),
        ),
    ]
