# Generated by Django 2.2.1 on 2019-05-14 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190514_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerspurchases',
            name='purchase_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 21, 28, 39, 869018), verbose_name='Purchase day'),
        ),
    ]
