# Generated by Django 2.2.1 on 2019-05-14 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190514_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerspurchases',
            name='purchase_day',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 5, 14, 21, 32, 30, 498753), verbose_name='Purchase day'),
        ),
    ]
