# Generated by Django 2.2.1 on 2019-05-14 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190514_2132'),
        ('api', '0007_auto_20190514_1520'),
    ]

    operations = [
    ]
