
from api.models import *

group1 = Group.objects.create(title="Системы счисления и СИ", background_color="3300CC", price=0)
group2 = Group.objects.create(title="Футбол: Новичок", background_color="99CC33", price=0)
group3 = Group.objects.create(title="Сериалы: Игра Престолов", background_color="66CCCC", price=0)
group4 = Group.objects.create(title="Фильмы: Марвел", background_color="660000", price=4)
group5 = Group.objects.create(title="Футбол: Любитель", background_color="009933", price=5)


question1 = Qa.objects.create(id_group=group1, question="Приставка Кило обозначает:", answer_1="10^3", answer_2="10^5", answer_3="100", answer_4="10^(-3)", answer_right="1")
question2 = Qa.objects.create(id_group=group1, question="Сколько байт в 20 килобайтах?", answer_1="20000", answer_2="160", answer_3="20480", answer_4="2*10^4", answer_right="3")
question3 = Qa.objects.create(id_group=group1, question="Выберите приставку, обозначающую самую малую величину среди перечисленных:", answer_1="Мили", answer_2="Санти", answer_3="Пета", answer_4="Пико", answer_right="4")
question4 = Qa.objects.create(id_group=group1, question="10^(-9) соответствует приставке:", answer_1="Нано", answer_2="Микро", answer_3="Мили", answer_4="Санти", answer_right="1")
question5 = Qa.objects.create(id_group=group1, question="101 в двоичной системе исчисления при переводе в десятичную будет равно:", answer_1="2", answer_2="5", answer_3="1", answer_4="3", answer_right="2")
question6 = Qa.objects.create(id_group=group1, question="Выберите приставку, обозначающую самую наибольшую величину среди перечисленных:", answer_1="Мили", answer_2="Санти", answer_3="Пета", answer_4="Мега", answer_right="3")
question7 = Qa.objects.create(id_group=group1, question="12 в восьмеричной системе исчисления при переводе в десятичную будет равно:", answer_1="2", answer_2="8", answer_3="10", answer_4="0", answer_right="3")
question8 = Qa.objects.create(id_group=group1, question="Сколько байт в 8 Байтах?", answer_1="8", answer_2="64", answer_3="2", answer_4="32", answer_right="1")
question9 = Qa.objects.create(id_group=group1, question="Не относится к приставкам с положительным множителем:", answer_1="Пико", answer_2="Мега", answer_3="Гекто", answer_4="Дека", answer_right="1")
question10 = Qa.objects.create(id_group=group1, question="С помощью одного байта можно закодировать:", answer_1="Целое число от 0 до 1024", answer_2="Целое число от 0 до 1000", answer_3="Целое число от 0 до 10^3", answer_4="Целое число от 0 до 255", answer_right="4")
question11 = Qa.objects.create(id_group=group2, question="Сколько людей находятся на поле во время футбольного матча?", answer_1="22", answer_2="23", answer_3="24", answer_4="25", answer_right="2")
question12 = Qa.objects.create(id_group=group2, question="Кто такой хавбэк?", answer_1="вратарь", answer_2="тренер", answer_3="нападающий", answer_4="полузащитник", answer_right="4")
question13 = Qa.objects.create(id_group=group2, question="Как в США называется европейский футбол?", answer_1="Регби", answer_2="Соккер", answer_3="Бэйсбол", answer_4="Гандбол", answer_right="2")
question14 = Qa.objects.create(id_group=group2, question="Сколько команд участвует в четверть финале кубка?", answer_1="16", answer_2="8", answer_3="4", answer_4="32", answer_right="2")
question15 = Qa.objects.create(id_group=group2, question="Самый престижный европейский клубный турнир?", answer_1="Лига Европы", answer_2="Суперкубок УЕФА", answer_3="Чемпионат Мира", answer_4="Лига Чемпионов", answer_right="4")
question16 = Qa.objects.create(id_group=group2, question="Сколько минут длится полноценный футбольный матч?", answer_1="120", answer_2="60", answer_3="90", answer_4="75", answer_right="3")
question17 = Qa.objects.create(id_group=group2, question="Как звучит неофициальное название чемпионата мира по футболу?", answer_1="Миндаль", answer_2="Муриаль", answer_3="Мундиаль", answer_4="Мирабель", answer_right="3")
question18 = Qa.objects.create(id_group=group2, question="Единственный вратарь в мире, который удостоился награды Золотой мяч?", answer_1="Буффон", answer_2="Касильяс", answer_3="Яшин", answer_4="Нойер", answer_right="3")
question19 = Qa.objects.create(id_group=group2, question="Сколько очков получает команда в случае ничьи?", answer_1="0", answer_2="1", answer_3="2", answer_4="3", answer_right="2")
question20 = Qa.objects.create(id_group=group2, question="Какое количество голов забивается при пента-трике?", answer_1="5", answer_2="4", answer_3="", answer_4="2", answer_right="1")
question21 = Qa.objects.create(id_group=group3, question="Сколько сезонов в Игре Престолов?", answer_1="5", answer_2="11", answer_3="8", answer_4="7", answer_right="3")
question22 = Qa.objects.create(id_group=group3, question="Как звучит девиз дома Ланнистеров?", answer_1="Ибо ночь темна и полна ужасов", answer_2="Ланнистеры всегда платят долги", answer_3="Зима близко", answer_4="Услышь мой рёв", answer_right="4")
question23 = Qa.objects.create(id_group=group3, question="Кто прибыл на помощь Джону Сноу в конце серии «За стеной», чтобы спасти его от ходоков и отправить к Восточному дозору?", answer_1="Дейенерис", answer_2="Бенджен", answer_3="Тормунд", answer_4="Сэм", answer_right="2")
question24 = Qa.objects.create(id_group=group3, question="Каждому из трех своих драконов Дейенерис дала имя. Какое из нижеперечисленных слов не является именем?", answer_1="Дрогон", answer_2="Визерион", answer_3="Рейгаль", answer_4="Дракарис", answer_right="4")
question25 = Qa.objects.create(id_group=group3, question="Какой из этих городов расположен севернее остальных?", answer_1="Браавос", answer_2="Юнкай", answer_3="Пентос", answer_4="Королевская гавань", answer_right="1")
question26 = Qa.objects.create(id_group=group3, question="Кому принадлежит эта цитата: «Есть только один бог, и имя его — смерть. А смерти мы говорим только одно — «Не сегодня»?", answer_1="Нэд Старк", answer_2="Джейме Ланистер", answer_3="Сирио Форель", answer_4="Петир Бейлиш", answer_right="3")
question27 = Qa.objects.create(id_group=group3, question="На красной свадьбе были жестоко убиты Робб Старк, его жена Талиса, мать Кейтилин и их знаменосцы и солдаты По какому сигналу на Старков напали?", answer_1="Арбалетчики, переодетые в музыкантов", answer_2="Подача вина", answer_3="Убийство Талисы ножом в живот", answer_4="Крик: «Встречайте Короля Севера!»", answer_right="1")
question28 = Qa.objects.create(id_group=group3, question="Кто населял Вестерос раньше?", answer_1="Андалы", answer_2="Первые люди", answer_3="Дети леса", answer_4="Белые ходоки", answer_right="3")
question29 = Qa.objects.create(id_group=group3, question="Кому поклоняются в черно-белом доме, который в сериале также служил еще и храмом?", answer_1="Неведомому", answer_2="Многоликому богу", answer_3="Рглору – Владыке света", answer_4="Богу смерти", answer_right="2")
question30 = Qa.objects.create(id_group=group3, question="Кто сядет на железный трон?", answer_1="Дейенерис", answer_2="Джон Сноу", answer_3="Тирион", answer_4="Узнаем в 6 серии 8 сезона", answer_right="4")
question41 = Qa.objects.create(id_group=group4, question="Сколько сезонов в Игре Престолов?", answer_1="5", answer_2="11", answer_3="8", answer_4="7", answer_right="3")
question42 = Qa.objects.create(id_group=group4, question="Как звучит девиз дома Ланнистеров?", answer_1="Ибо ночь темна и полна ужасов", answer_2="Ланнистеры всегда платят долги", answer_3="Зима близко", answer_4="Услышь мой рёв", answer_right="4")
question43 = Qa.objects.create(id_group=group4, question="Кто прибыл на помощь Джону Сноу в конце серии «За стеной», чтобы спасти его от ходоков и отправить к Восточному дозору?", answer_1="Дейенерис", answer_2="Бенджен", answer_3="Тормунд", answer_4="Сэм", answer_right="2")
question44 = Qa.objects.create(id_group=group4, question="Каждому из трех своих драконов Дейенерис дала имя. Какое из нижеперечисленных слов не является именем?", answer_1="Дрогон", answer_2="Визерион", answer_3="Рейгаль", answer_4="Дракарис", answer_right="4")
question45 = Qa.objects.create(id_group=group4, question="Какой из этих городов расположен севернее остальных?", answer_1="Браавос", answer_2="Юнкай", answer_3="Пентос", answer_4="Королевская гавань", answer_right="1")
question46 = Qa.objects.create(id_group=group4, question="Кому принадлежит эта цитата: «Есть только один бог, и имя его — смерть. А смерти мы говорим только одно — «Не сегодня»?", answer_1="Нэд Старк", answer_2="Джейме Ланистер", answer_3="Сирио Форель", answer_4="Петир Бейлиш", answer_right="3")
question47 = Qa.objects.create(id_group=group4, question="На красной свадьбе были жестоко убиты Робб Старк, его жена Талиса, мать Кейтилин и их знаменосцы и солдаты По какому сигналу на Старков напали?", answer_1="Арбалетчики, переодетые в музыкантов", answer_2="Подача вина", answer_3="Убийство Талисы ножом в живот", answer_4="Крик: «Встречайте Короля Севера!»", answer_right="1")
question48 = Qa.objects.create(id_group=group4, question="Кто населял Вестерос раньше?", answer_1="Андалы", answer_2="Первые люди", answer_3="Дети леса", answer_4="Белые ходоки", answer_right="3")
question49 = Qa.objects.create(id_group=group4, question="Кому поклоняются в черно-белом доме, который в сериале также служил еще и храмом?", answer_1="Неведомому", answer_2="Многоликому богу", answer_3="Рглору – Владыке света", answer_4="Богу смерти", answer_right="2")
question50 = Qa.objects.create(id_group=group4, question="Кто сядет на железный трон?", answer_1="Дейенерис", answer_2="Джон Сноу", answer_3="Тирион", answer_4="Узнаем в 6 серии 8 сезона", answer_right="4")
question51 = Qa.objects.create(id_group=group5, question="Сколько людей находятся на поле во время футбольного матча?", answer_1="22", answer_2="23", answer_3="24", answer_4="25", answer_right="2")
question52 = Qa.objects.create(id_group=group5, question="Кто такой хавбэк?", answer_1="вратарь", answer_2="тренер", answer_3="нападающий", answer_4="полузащитник", answer_right="4")
question53 = Qa.objects.create(id_group=group5, question="Как в США называется европейский футбол?", answer_1="Регби", answer_2="Соккер", answer_3="Бэйсбол", answer_4="Гандбол", answer_right="2")
question54 = Qa.objects.create(id_group=group5, question="Сколько команд участвует в четверть финале кубка?", answer_1="16", answer_2="8", answer_3="4", answer_4="32", answer_right="2")
question55 = Qa.objects.create(id_group=group5, question="Самый престижный европейский клубный турнир?", answer_1="Лига Европы", answer_2="Суперкубок УЕФА", answer_3="Чемпионат Мира", answer_4="Лига Чемпионов", answer_right="4")
question56 = Qa.objects.create(id_group=group5, question="Сколько минут длится полноценный футбольный матч?", answer_1="120", answer_2="60", answer_3="90", answer_4="75", answer_right="3")
question57 = Qa.objects.create(id_group=group5, question="Как звучит неофициальное название чемпионата мира по футболу?", answer_1="Миндаль", answer_2="Муриаль", answer_3="Мундиаль", answer_4="Мирабель", answer_right="3")
question58 = Qa.objects.create(id_group=group5, question="Единственный вратарь в мире, который удостоился награды Золотой мяч?", answer_1="Буффон", answer_2="Касильяс", answer_3="Яшин", answer_4="Нойер", answer_right="3")
question59 = Qa.objects.create(id_group=group5, question="Сколько очков получает команда в случае ничьи?", answer_1="0", answer_2="1", answer_3="2", answer_4="3", answer_right="2")
question60 = Qa.objects.create(id_group=group5, question="Какое количество голов забивается при пента-трике?", answer_1="5", answer_2="4", answer_3="", answer_4="2", answer_right="1")